CREATE DATABASE IF NOT EXISTS QuanLyBanHang;
USE QuanLyBanHang;
CREATE TABLE Customer(
	cID INT PRIMARY KEY AUTO_INCREMENT,
    cName VARCHAR(200) NOT NULL, 
    cAge INT NOT NULL DEFAULT 1 CHECK (cAge > 0)
);

CREATE TABLE Orders(
	oID INT PRIMARY KEY AUTO_INCREMENT,
    cID INT NOT NULL, 
    oDate DATE, 
    oTotalPrice DECIMAL(10,2) CHECK(oTotalPrice > 0),
    FOREIGN KEY (cID) REFERENCES Customer(cID)
);

CREATE TABLE Product(
	pID INT PRIMARY KEY AUTO_INCREMENT,
    pName VARCHAR(200) NOT NULL, 
    pPrice DECIMAL(10,2) CHECK(pPrice > 0) 
);

CREATE TABLE OrderDetail(
	oID INT NOT NULL,
	pID INT NOT NULL,
    PRIMARY KEY(oID, pID),
    odQTY INT CHECK(odQTY > 0),
    FOREIGN KEY (oID) REFERENCES Orders(oID),
    FOREIGN KEY (pID) REFERENCES Product(pID)
);

